# configs/default_config.yaml

data:
  raw_dir: "data/raw"
  manual_dir: "data/manually_adjustments"
  processed_dir: "data/processed"
  splits_dir: "data/splits"
  split_ratios: [0.7, 0.15, 0.15]

preprocessing:
  voxel_size: 0.02
  num_points: 2048
  noise_params:
    mean: 0.0
    std: 0.02

training:
  batch_size: 2
  num_epochs: 50
  learning_rate: 0.001
  scheduler_step_size: 20
  scheduler_gamma: 0.5
  num_classes: 2

model:
  num_points: 4096
  save_dir: "models/checkpoints"

